'use strict'

var gProgects = [{

    id: "touch-nums",
    name: "touch-nums",
    title: "click all the numbers",
    desc: "click them as fast as u can",
    url: "projs/touch-nums",
    publishedAt: "",
    labels: ["Matrix", "keyboard events"],
},
{
    id: "touch-nums",
    name: "touch-nums",
    title: "click all the numbers",
    desc: "click them as fast as u can",
    url: "projs/touch-nums",
    publishedAt: "",
    labels: ["Matrix", "keyboard events"],
},
{
    id: "touch-nums",
    name: "touch-nums",
    title: "click all the numbers",
    desc: "click them as fast as u can",
    url: "projs/touch-nums",
    publishedAt: "",
    labels: ["Matrix", "keyboard events"],
},
{
    id: "touch-nums",
    name: "touch-nums",
    title: "click all the numbers",
    desc: "click them as fast as u can",
    url: "projs/touch-nums",
    publishedAt: "",
    labels: ["Matrix", "keyboard events"],
},
{
    id: "touch-nums",
    name: "touch-nums",
    title: "click all the numbers",
    desc: "click them as fast as u can",
    url: "projs/touch-nums",
    publishedAt: "",
    labels: ["Matrix", "keyboard events"],
},
{
    id: "touch-nums",
    name: "touch-nums",
    title: "click all the numbers",
    desc: "click them as fast as u can",
    url: "projs/touch-nums",
    publishedAt: "",
    labels: ["Matrix", "keyboard events"],
},
]